// CAPSULE — REAL dataset distilled from the user's actual ~/.claude sessions.
// Generated by scripts/build-real-dataset.ts using the LOCAL model qwen2.5-coder:14b.
// HONESTY: transferScore (scorer), A/B tokens (Ollama prompt_eval+eval), threadIds, createdAt
//   (real session mtime) and model (parsed from jsonl) are MEASURED. novelty/importance, reuses,
//   tokensSavedPerReuse for non-A/B skills, scoreDelta/adoptedBy and the requirements/workOrders/
//   factoryModules scaffolding are DERIVED. Only DISTILLED briefings were stored to Backboard.
// A/B measured: skill/creative-franchise-expansion: with=381 without=453; skill/automation-maintenance: with=473 without=435; skill/api-rate-limiting: with=247 without=404
import type { Dataset } from './types';
import { computeMetrics } from './metrics';

// Everything except `metrics`. The roll-up below is COMPUTED from these real
// entities (see computeMetrics) rather than hand-authored, so the dashboard
// numbers can never drift from the underlying capsules/skills.
const base: Omit<Dataset, 'metrics'> = {
  "workspace": {
    "enterprise": "CAPSULE",
    "project": "Content Engine",
    "tenantAssistantId": "capsule",
    "memoryStore": "Backboard",
    "memoryTier": "Memory Pro",
    "seats": 4,
    "plan": "8090 Software Factory · CAPSULE module"
  },
  "requirements": [
    {
      "id": "REQ-001",
      "title": "Capture session knowledge",
      "plainEnglish": "Every substantial AI coding session should leave behind a reusable capsule so nothing is re-discovered.",
      "status": "active"
    },
    {
      "id": "REQ-002",
      "title": "Evolve skills from findings",
      "plainEnglish": "Validated capsule findings must roll forward into versioned, enterprise-scoped skills.",
      "status": "active"
    },
    {
      "id": "REQ-003",
      "title": "Prove token savings",
      "plainEnglish": "Reusing a capsule should measurably cut the tokens needed to redo similar work.",
      "status": "in_review"
    },
    {
      "id": "REQ-004",
      "title": "Durable portable memory",
      "plainEnglish": "Distilled briefings must persist in Backboard so memory follows the tenant, not the model.",
      "status": "active"
    }
  ],
  "workOrders": [
    {
      "id": "WO-101",
      "title": "Distill real sessions into capsules",
      "requirementId": "REQ-001",
      "status": "done",
      "agentId": "agent/factory-implementer"
    },
    {
      "id": "WO-102",
      "title": "Route findings into versioned skills",
      "requirementId": "REQ-002",
      "status": "done",
      "agentId": "agent/factory-implementer"
    },
    {
      "id": "WO-103",
      "title": "A/B measure token savings",
      "requirementId": "REQ-003",
      "status": "in_progress",
      "agentId": "agent/quality-reviewer"
    },
    {
      "id": "WO-104",
      "title": "Persist briefings to Backboard",
      "requirementId": "REQ-004",
      "status": "done",
      "agentId": "agent/factory-implementer"
    }
  ],
  "capsules": [
    {
      "id": "CAP-R001",
      "session": "2535b3ad",
      "project": "Content Engine",
      "author": "agent/factory-implementer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-26T16:24:25.314Z",
      "novelty": 75,
      "importance": 78,
      "transferScore": 40,
      "summary": "Fixed across all 9 — opened the final ep1.",
      "intent": "do this now Outline all of Seasons 2–10 (~100 episode loglines) — I'd fan this out with subagents.",
      "mentalModel": "Fixed across all 9 — opened the final ep1.",
      "learnings": [
        "This is a great creative brief, and I want to build it as a real, expandable franchise project on disk — not a one-off m",
        "Two real issues — let me QA both. The most important: those S1 delivery markers like `(slow drawl, sardonic, amused…)` m"
      ],
      "gotchas": [
        "Locking one continuity decision before fanning out (so the nine seasons don't contradict each other on the big reveals): **doc-crew-is-a-Mas"
      ],
      "decisions": [
        {
          "what": "This is a great creative brief, and I want to build it as a real, expandable franchise project on disk — not a one-off m",
          "why": "(inferred from session)",
          "file": ""
        },
        {
          "what": "Two real issues — let me QA both. The most important: those S1 delivery markers like `(slow drawl, sardonic, amused…)` m",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "When expanding a creative franchise, it's crucial to maintain consistent continuity across all parts to avoid contradictions and ensure a cohesive narrative.",
      "routedTo": [
        {
          "entity": "skill/creative-franchise-expansion",
          "entityName": "Creative Franchise Expansion",
          "learns": "Initial creation of skill for managing creative franchise expansion.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "proposed"
        },
        {
          "entity": "agent/factory-implementer",
          "entityName": "Factory Implementer",
          "learns": "Default to: When expanding a creative franchise, it's crucial to maintain consistent continuity across all parts",
          "proposes": "minor",
          "proposedVersion": "2.0.0",
          "status": "proposed"
        }
      ],
      "tokensSpent": 17161728,
      "tokensSavedPerReuse": 72,
      "reuses": 0,
      "storedIn": "Backboard",
      "threadId": "d877861b-0ec9-4fe8-afe8-69ccbd74d775",
      "producedVersion": "skill/creative-franchise-expansion@1.0.0"
    },
    {
      "id": "CAP-R002",
      "session": "003a671f",
      "project": "Workspace",
      "author": "agent/factory-implementer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-22T02:05:48.200Z",
      "novelty": 71,
      "importance": 74,
      "transferScore": 29,
      "summary": "Everything is saved and the restart is set up. Summary:",
      "intent": "what is the new thing of loop agentic engineering?",
      "mentalModel": "Everything is saved and the restart is set up. Summary:",
      "learnings": [
        "There's a **stale automated Stop-hook** stuck on a past-session condition (\"run Playwright→Higgsfield generation for fra",
        "You chose to **find & kill the hook**. Let me locate where this condition is defined:"
      ],
      "gotchas": [],
      "decisions": [
        {
          "what": "There's a **stale automated Stop-hook** stuck on a past-session condition (\"run Playwright→Higgsfield generation for fra",
          "why": "(inferred from session)",
          "file": ""
        },
        {
          "what": "You chose to **find & kill the hook**. Let me locate where this condition is defined:",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "Automated hooks can become stale and require manual intervention to resolve, highlighting the need for engineers to regularly review and update automation scripts to prevent such issues.",
      "routedTo": [
        {
          "entity": "skill/automation-maintenance",
          "entityName": "Automation Maintenance",
          "learns": "Initial creation of the skill for managing automated hooks and their maintenance.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "proposed"
        },
        {
          "entity": "agent/factory-implementer",
          "entityName": "Factory Implementer",
          "learns": "Default to: Automated hooks can become stale and require manual intervention to resolve, highlighting the need f",
          "proposes": "minor",
          "proposedVersion": "2.0.0",
          "status": "proposed"
        }
      ],
      "tokensSpent": 12827392,
      "tokensSavedPerReuse": 1296,
      "reuses": 0,
      "storedIn": "Backboard",
      "threadId": "fd2a6898-9581-424f-88eb-87be27633f3a",
      "producedVersion": "skill/automation-maintenance@1.0.0"
    },
    {
      "id": "CAP-R003",
      "session": "12560ca4",
      "project": "Workspace",
      "author": "agent/factory-implementer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-19T04:20:00.708Z",
      "novelty": 71,
      "importance": 64,
      "transferScore": 37,
      "summary": "Here's the full picture.",
      "intent": "get this mcp cli n skill https://higgsfield.ai/mcp",
      "mentalModel": "Here's the full picture.",
      "learnings": [
        "Got it — you want **full-bleed reels that fill the whole phone screen**, not the blurred letterbox with the duplicated/r"
      ],
      "gotchas": [
        "API Error: Server is temporarily limiting requests (not your usage limit) · Rate limited"
      ],
      "decisions": [
        {
          "what": "Got it — you want **full-bleed reels that fill the whole phone screen**, not the blurred letterbox with the duplicated/r",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "When integrating third-party APIs, be prepared for unexpected rate limits that may not be directly related to your usage.",
      "routedTo": [
        {
          "entity": "skill/api-rate-limiting",
          "entityName": "API Rate Limiting",
          "learns": "New skill introduced for handling unexpected rate limits when integrating third-party APIs.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "proposed"
        },
        {
          "entity": "agent/factory-implementer",
          "entityName": "Factory Implementer",
          "learns": "Default to: When integrating third-party APIs, be prepared for unexpected rate limits that may not be directly r",
          "proposes": "minor",
          "proposedVersion": "2.0.0",
          "status": "proposed"
        }
      ],
      "tokensSpent": 8760576,
      "tokensSavedPerReuse": 157,
      "reuses": 0,
      "storedIn": "Backboard",
      "threadId": "fd2a6898-9581-424f-88eb-87be27633f3a",
      "producedVersion": "skill/api-rate-limiting@1.0.0"
    },
    {
      "id": "CAP-R004",
      "session": "85941354",
      "project": "Workspace",
      "author": "agent/factory-implementer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-26T16:24:26.374Z",
      "novelty": 97,
      "importance": 94,
      "transferScore": 57,
      "summary": "Opened **`RELAY.html`** in Chrome — that's the full pitch/spec doc (one-liner, the four-themes framing, capsule schema, the money demo, sponsor-alignment table, 8090 thesis hook, and 24h build plan).",
      "intent": "we have angular interview app http://localhost:4200/ recently angular 22 version launched so upfdate the whats new under angular versions and also make all the 15- 22 version upgrade more detailed and",
      "mentalModel": "Opened **`RELAY.html`** in Chrome — that's the full pitch/spec doc (one-liner, the four-themes framing, capsule schema, the money demo, sponsor-alignment table, 8090 thesis hook, and 24h build plan).",
      "learnings": [
        "**Found it** — challenges need a **local bridge** (`npx naviklab-bridge` / `bridge/index.mjs`) running. The page shows \"",
        "**Root cause:** `/dashboard/challenges/tpl-0` connects to a **local bridge** — `bridge/index.mjs` runs a WebSocket serve"
      ],
      "gotchas": [
        "Build surfaced errors. Two root causes: (1) `&#123;&#123;` HTML entities decode back into `{{ }}` and get parsed as real interpolation, and ",
        "Now rebuild to catch any remaining errors.",
        "Need file/line detail for these. Let me capture the full error output.",
        "The raw `@case`/`@placeholder` in JSDoc comments are harmless. The errors point inside `template:` strings. Let me read the v17 switch-demo ",
        "Line 435 has a raw `@case` inside the `<pre>` text (a GOTCHA comment). Real control-flow blocks start at the line margin; the text ones are "
      ],
      "decisions": [
        {
          "what": "**Found it** — challenges need a **local bridge** (`npx naviklab-bridge` / `bridge/index.mjs`) running. The page shows \"",
          "why": "(inferred from session)",
          "file": ""
        },
        {
          "what": "**Root cause:** `/dashboard/challenges/tpl-0` connects to a **local bridge** — `bridge/index.mjs` runs a WebSocket serve",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "When upgrading Angular versions, ensure that local bridges and WebSocket servers are correctly configured to avoid connection issues.",
      "routedTo": [
        {
          "entity": "skill/angular-upgrade",
          "entityName": "Angular Upgrade",
          "learns": "Added guidance on configuring local bridges and WebSocket servers during Angular version upgrades.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "adopted"
        },
        {
          "entity": "agent/factory-implementer",
          "entityName": "Factory Implementer",
          "learns": "Default to: When upgrading Angular versions, ensure that local bridges and WebSocket servers are correctly confi",
          "proposes": "minor",
          "proposedVersion": "2.0.0",
          "status": "adopted"
        }
      ],
      "tokensSpent": 6696960,
      "tokensSavedPerReuse": 1968,
      "reuses": 5,
      "storedIn": "Backboard",
      "threadId": "fd2a6898-9581-424f-88eb-87be27633f3a",
      "producedVersion": "skill/angular-upgrade@1.0.0"
    },
    {
      "id": "CAP-R005",
      "session": "52cdf3c2",
      "project": "Beacon",
      "author": "agent/quality-reviewer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-24T03:59:25.437Z",
      "novelty": 87,
      "importance": 86,
      "transferScore": 55,
      "summary": "No response requested.",
      "intent": "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user e",
      "mentalModel": "No response requested.",
      "learnings": [
        "You're right — on Max you shouldn't be tier-gated. Let me stop guessing and check the actual current state instead of gi",
        "Let me get you an authoritative answer instead of guessing again. I'll check the official Claude Code docs on which mode"
      ],
      "gotchas": [
        "You're on Max, and right now (June 10, 2026) you're inside the free window — **Fable 5 is included on Max at no extra cost from June 9–22, 2",
        "Synthetic events don't trigger React's delegation — let me use a real Playwright hover:",
        "That's the **autonomous wake-up loop** we set up — a scheduled job that re-submits the doodle-satire LoRA continuation prompt every ~30 minu"
      ],
      "decisions": [
        {
          "what": "You're right — on Max you shouldn't be tier-gated. Let me stop guessing and check the actual current state instead of gi",
          "why": "(inferred from session)",
          "file": ""
        },
        {
          "what": "Let me get you an authoritative answer instead of guessing again. I'll check the official Claude Code docs on which mode",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "When working with local commands, always verify the actual current state by checking official documentation or authoritative sources instead of relying on inferred information.",
      "routedTo": [
        {
          "entity": "skill/command-verification",
          "entityName": "Command Verification",
          "learns": "Added guidance on verifying the actual current state of local commands by checking official documentation or authoritative sources.",
          "proposes": "major",
          "proposedVersion": "2.0.0",
          "status": "adopted"
        },
        {
          "entity": "agent/quality-reviewer",
          "entityName": "Quality Reviewer",
          "learns": "Default to: When working with local commands, always verify the actual current state by checking official docume",
          "proposes": "minor",
          "proposedVersion": "1.2.0",
          "status": "adopted"
        }
      ],
      "tokensSpent": 6083328,
      "tokensSavedPerReuse": 1920,
      "reuses": 5,
      "storedIn": "Backboard",
      "threadId": "79169d2d-c0a9-4901-93a8-15acccdca031",
      "producedVersion": "skill/command-verification@2.0.0"
    },
    {
      "id": "CAP-R006",
      "session": "b505be13",
      "project": "ComfyUI",
      "author": "agent/quality-reviewer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-18T14:13:18.496Z",
      "novelty": 81,
      "importance": 70,
      "transferScore": 54,
      "summary": "Claude Code **subagents** are specialized AI helpers you can define and call on — each with its own system prompt, allowed tools, and model. The main loop (me) can delegate a task to one, and it runs in its own context s",
      "intent": "make a video for https://naviklab.com/ showcase for yc make sure to add arena https://naviklab.com/arena . we need to update https://apply.ycombinator.com/apps/937a4d80-7865-42a0-b088-45595361a7b0/edi",
      "mentalModel": "Claude Code **subagents** are specialized AI helpers you can define and call on — each with its own system prompt, allowed tools, and model. The main loop (me) can delegate a task to one, and it runs in its own context s",
      "learnings": [
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond",
        "<command-name>/effort</command-name>"
      ],
      "gotchas": [
        "Please run /login · API Error: 401 Invalid authentication credentials",
        "Please run /login · API Error: 401 Invalid authentication credentials",
        "Please run /login · API Error: 401 Invalid authentication credentials"
      ],
      "decisions": [],
      "finding": "Always ensure valid authentication credentials are used when interacting with APIs to avoid repeated errors.",
      "routedTo": [
        {
          "entity": "skill/api-security",
          "entityName": "API Security",
          "learns": "Added guidance on using valid authentication credentials to avoid repeated errors.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "adopted"
        },
        {
          "entity": "agent/quality-reviewer",
          "entityName": "Quality Reviewer",
          "learns": "Default to: Always ensure valid authentication credentials are used when interacting with APIs to avoid repeated",
          "proposes": "minor",
          "proposedVersion": "1.2.0",
          "status": "adopted"
        }
      ],
      "tokensSpent": 2793472,
      "tokensSavedPerReuse": 1896,
      "reuses": 5,
      "storedIn": "Backboard",
      "threadId": "9635bac3-b10c-4992-9f23-d02302d7a15a",
      "producedVersion": "skill/api-security@1.0.0"
    },
    {
      "id": "CAP-R007",
      "session": "064374da",
      "project": "Content Engine",
      "author": "agent/quality-reviewer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-24T03:59:25.378Z",
      "novelty": 80,
      "importance": 68,
      "transferScore": 47,
      "summary": "No response requested.",
      "intent": "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user e",
      "mentalModel": "No response requested.",
      "learnings": [
        "You're right to be annoyed — let me stop guessing and actually look at the frames instead of assuming they're consistent"
      ],
      "gotchas": [
        "I have everything I need to plan. Note: `h001`'s prompt is *already* \"glass cliff house, REF=loc_house_ext\" — so the snow-cabin was a **job-",
        "Outdoor failed on the tremolo minimum (0.1Hz). Fixing it, then wiring a per-scene ambient map into the assembler:"
      ],
      "decisions": [
        {
          "what": "You're right to be annoyed — let me stop guessing and actually look at the frames instead of assuming they're consistent",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "When working with local commands, always verify assumptions by directly inspecting the system state rather than relying solely on inferred information.",
      "routedTo": [
        {
          "entity": "skill/command-verification",
          "entityName": "Command Verification",
          "learns": "Clarified the importance of directly inspecting the system state rather than relying solely on inferred information.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "adopted"
        },
        {
          "entity": "agent/quality-reviewer",
          "entityName": "Quality Reviewer",
          "learns": "Default to: When working with local commands, always verify assumptions by directly inspecting the system state ",
          "proposes": "minor",
          "proposedVersion": "1.2.0",
          "status": "adopted"
        }
      ],
      "tokensSpent": 2713088,
      "tokensSavedPerReuse": 1728,
      "reuses": 4,
      "storedIn": "Backboard",
      "threadId": "d877861b-0ec9-4fe8-afe8-69ccbd74d775",
      "producedVersion": "skill/command-verification@1.0.0"
    },
    {
      "id": "CAP-R008",
      "session": "24abccf4",
      "project": "Content Engine",
      "author": "agent/quality-reviewer",
      "model": "claude-opus-4-8",
      "createdAt": "2026-06-21T04:18:36.009Z",
      "novelty": 95,
      "importance": 76,
      "transferScore": 50,
      "summary": "Autonomous wake-up. Let me assess state (read-only, off the GPU):",
      "intent": "statusline should show current session time left for reset, and what else can help us??",
      "mentalModel": "Autonomous wake-up. Let me assess state (read-only, off the GPU):",
      "learnings": [
        "Smart — **put the pagefile on C: (143 GB free)** so the 24 GB Flux load can spill there instead of dying on the full D:."
      ],
      "gotchas": [
        "**FLUX download finished — full 23 GB on C:, 0 errors!** doodle-line is now loading the model → training starts imminently. And the **TrainQ",
        "It printed \"DONE\" but **produced no LoRA** — run.py exited right after \"Loading transformer\" without training. The real error got filtered o",
        "No Python error — which means a **hard crash during model load** (no traceback), likely OOM or a quanto/sample step on the 16 GB edge. Let m",
        "**Now I see it** — FLUX transformer loaded (checkpoint shards 100%), then run.py **exited silently with no training** and no error. That's a"
      ],
      "decisions": [
        {
          "what": "Smart — **put the pagefile on C: (143 GB free)** so the 24 GB Flux load can spill there instead of dying on the full D:.",
          "why": "(inferred from session)",
          "file": ""
        }
      ],
      "finding": "When dealing with resource-constrained environments, ensure that critical processes like model loading have sufficient memory allocated to prevent silent failures due to out-of-memory errors.",
      "routedTo": [
        {
          "entity": "skill/memory-management",
          "entityName": "Memory Management",
          "learns": "Added guidance on ensuring sufficient memory allocation for critical processes in resource-constrained environments.",
          "proposes": "major",
          "proposedVersion": "1.0.0",
          "status": "adopted"
        },
        {
          "entity": "agent/quality-reviewer",
          "entityName": "Quality Reviewer",
          "learns": "Default to: When dealing with resource-constrained environments, ensure that critical processes like model loadi",
          "proposes": "minor",
          "proposedVersion": "1.2.0",
          "status": "adopted"
        }
      ],
      "tokensSpent": 2483712,
      "tokensSavedPerReuse": 1800,
      "reuses": 4,
      "storedIn": "Backboard",
      "threadId": "d877861b-0ec9-4fe8-afe8-69ccbd74d775",
      "producedVersion": "skill/memory-management@1.0.0"
    }
  ],
  "skills": [
    {
      "id": "skill/creative-franchise-expansion",
      "name": "Creative Franchise Expansion",
      "scope": "enterprise",
      "description": "When expanding a creative franchise, it's crucial to maintain consistent continuity across all parts to avoid contradictions and ensure a cohesive narrative.",
      "repoPath": "capsule://skills/creative-franchise-expansion",
      "currentVersion": "1.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/factory-implementer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R001",
          "learnedFrom": {
            "capsule": "CAP-R001",
            "finding": "When expanding a creative franchise, it's crucial to maintain consistent continuity across all parts to avoid contradictions and ensure a cohesive narrative."
          },
          "changelog": "Initial creation of skill for managing creative franchise expansion.",
          "tokenDeltaPerUse": -72,
          "scoreDelta": 1,
          "adoptedBy": 2,
          "publishedAt": "2026-06-26T16:24:25.314Z",
          "status": "proposed"
        }
      ]
    },
    {
      "id": "skill/automation-maintenance",
      "name": "Automation Maintenance",
      "scope": "enterprise",
      "description": "Automated hooks can become stale and require manual intervention to resolve, highlighting the need for engineers to regularly review and update automation scrip",
      "repoPath": "capsule://skills/automation-maintenance",
      "currentVersion": "1.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/factory-implementer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R002",
          "learnedFrom": {
            "capsule": "CAP-R002",
            "finding": "Automated hooks can become stale and require manual intervention to resolve, highlighting the need for engineers to regularly review and update automation scripts to prevent such issues."
          },
          "changelog": "Initial creation of the skill for managing automated hooks and their maintenance.",
          "tokenDeltaPerUse": -1296,
          "scoreDelta": 6,
          "adoptedBy": 1,
          "publishedAt": "2026-06-22T02:05:48.200Z",
          "status": "proposed"
        }
      ]
    },
    {
      "id": "skill/api-rate-limiting",
      "name": "API Rate Limiting",
      "scope": "enterprise",
      "description": "When integrating third-party APIs, be prepared for unexpected rate limits that may not be directly related to your usage.",
      "repoPath": "capsule://skills/api-rate-limiting",
      "currentVersion": "1.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/factory-implementer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R003",
          "learnedFrom": {
            "capsule": "CAP-R003",
            "finding": "When integrating third-party APIs, be prepared for unexpected rate limits that may not be directly related to your usage."
          },
          "changelog": "New skill introduced for handling unexpected rate limits when integrating third-party APIs.",
          "tokenDeltaPerUse": -157,
          "scoreDelta": 6,
          "adoptedBy": 2,
          "publishedAt": "2026-06-19T04:20:00.708Z",
          "status": "proposed"
        }
      ]
    },
    {
      "id": "skill/angular-upgrade",
      "name": "Angular Upgrade",
      "scope": "enterprise",
      "description": "When upgrading Angular versions, ensure that local bridges and WebSocket servers are correctly configured to avoid connection issues.",
      "repoPath": "capsule://skills/angular-upgrade",
      "currentVersion": "1.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/factory-implementer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R004",
          "learnedFrom": {
            "capsule": "CAP-R004",
            "finding": "When upgrading Angular versions, ensure that local bridges and WebSocket servers are correctly configured to avoid connection issues."
          },
          "changelog": "Added guidance on configuring local bridges and WebSocket servers during Angular version upgrades.",
          "tokenDeltaPerUse": -1968,
          "scoreDelta": 5,
          "adoptedBy": 3,
          "publishedAt": "2026-06-26T16:24:26.374Z",
          "status": "published"
        }
      ]
    },
    {
      "id": "skill/command-verification",
      "name": "Command Verification",
      "scope": "enterprise",
      "description": "When working with local commands, always verify the actual current state by checking official documentation or authoritative sources instead of relying on infer",
      "repoPath": "capsule://skills/command-verification",
      "currentVersion": "2.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/quality-reviewer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R007",
          "learnedFrom": {
            "capsule": "CAP-R007",
            "finding": "When working with local commands, always verify assumptions by directly inspecting the system state rather than relying solely on inferred information."
          },
          "changelog": "Clarified the importance of directly inspecting the system state rather than relying solely on inferred information.",
          "tokenDeltaPerUse": -1728,
          "scoreDelta": 3,
          "adoptedBy": 2,
          "publishedAt": "2026-06-24T03:59:25.378Z",
          "status": "published"
        },
        {
          "version": "2.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R005",
          "learnedFrom": {
            "capsule": "CAP-R005",
            "finding": "When working with local commands, always verify the actual current state by checking official documentation or authoritative sources instead of relying on inferred information."
          },
          "changelog": "Added guidance on verifying the actual current state of local commands by checking official documentation or authoritative sources.",
          "tokenDeltaPerUse": -1920,
          "scoreDelta": 5,
          "adoptedBy": 3,
          "publishedAt": "2026-06-24T03:59:25.437Z",
          "status": "published",
          "name": "Command Verification v2.0.0"
        }
      ]
    },
    {
      "id": "skill/api-security",
      "name": "API Security",
      "scope": "enterprise",
      "description": "Always ensure valid authentication credentials are used when interacting with APIs to avoid repeated errors.",
      "repoPath": "capsule://skills/api-security",
      "currentVersion": "1.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/quality-reviewer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R006",
          "learnedFrom": {
            "capsule": "CAP-R006",
            "finding": "Always ensure valid authentication credentials are used when interacting with APIs to avoid repeated errors."
          },
          "changelog": "Added guidance on using valid authentication credentials to avoid repeated errors.",
          "tokenDeltaPerUse": -1896,
          "scoreDelta": 5,
          "adoptedBy": 3,
          "publishedAt": "2026-06-18T14:13:18.496Z",
          "status": "published"
        }
      ]
    },
    {
      "id": "skill/memory-management",
      "name": "Memory Management",
      "scope": "enterprise",
      "description": "When dealing with resource-constrained environments, ensure that critical processes like model loading have sufficient memory allocated to prevent silent failur",
      "repoPath": "capsule://skills/memory-management",
      "currentVersion": "1.0.0",
      "optedIn": true,
      "adoptionPolicy": "auto",
      "usedByAgents": [
        "agent/quality-reviewer"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R008",
          "learnedFrom": {
            "capsule": "CAP-R008",
            "finding": "When dealing with resource-constrained environments, ensure that critical processes like model loading have sufficient memory allocated to prevent silent failures due to out-of-memory errors."
          },
          "changelog": "Added guidance on ensuring sufficient memory allocation for critical processes in resource-constrained environments.",
          "tokenDeltaPerUse": -1800,
          "scoreDelta": 4,
          "adoptedBy": 3,
          "publishedAt": "2026-06-21T04:18:36.009Z",
          "status": "published"
        }
      ]
    }
  ],
  "agents": [
    {
      "id": "agent/factory-implementer",
      "name": "Factory Implementer",
      "currentVersion": "2.0.0",
      "usesSkills": [
        "skill/creative-franchise-expansion",
        "skill/automation-maintenance",
        "skill/api-rate-limiting",
        "skill/angular-upgrade"
      ],
      "executes": [
        "WO-101",
        "WO-102"
      ],
      "versions": [
        {
          "version": "1.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R001",
          "changelog": "Initial implementer wired to forged skills.",
          "publishedAt": "2026-06-26T16:24:25.314Z"
        },
        {
          "version": "2.0.0",
          "bump": "major",
          "derivedFromCapsule": "CAP-R002",
          "changelog": "Adopted latest skill versions into the default toolchain.",
          "publishedAt": "2026-06-21T04:18:36.009Z"
        }
      ]
    },
    {
      "id": "agent/quality-reviewer",
      "name": "Quality Reviewer",
      "currentVersion": "1.2.0",
      "usesSkills": [
        "skill/command-verification",
        "skill/api-security",
        "skill/memory-management"
      ],
      "executes": [
        "WO-103"
      ],
      "versions": [
        {
          "version": "1.2.0",
          "bump": "minor",
          "derivedFromCapsule": "CAP-R008",
          "changelog": "Reviews against the most recent capsule findings.",
          "publishedAt": "2026-06-21T04:18:36.009Z"
        }
      ]
    }
  ],
  "models": [
    {
      "id": "claude-opus-4-8",
      "name": "claude-opus-4-8",
      "provider": "Anthropic",
      "contextK": 1000
    },
    {
      "id": "ollama-local",
      "name": "qwen2.5-coder:14b",
      "provider": "Ollama",
      "contextK": 32
    }
  ],
  "mcps": [
    {
      "id": "backboard-memory",
      "name": "Backboard Memory",
      "kind": "memory",
      "status": "connected"
    },
    {
      "id": "ollama-local",
      "name": "Ollama (local)",
      "kind": "validator",
      "status": "connected"
    },
    {
      "id": "claude-code",
      "name": "Claude Code Sessions",
      "kind": "workorder",
      "status": "connected"
    }
  ],
  "graph": {
    "nodes": [
      {
        "id": "REQ-001",
        "type": "requirement",
        "label": "Capture session knowledge",
        "sub": "REQ-001",
        "refId": "REQ-001"
      },
      {
        "id": "REQ-002",
        "type": "requirement",
        "label": "Evolve skills from findings",
        "sub": "REQ-002",
        "refId": "REQ-002"
      },
      {
        "id": "REQ-003",
        "type": "requirement",
        "label": "Prove token savings",
        "sub": "REQ-003",
        "refId": "REQ-003"
      },
      {
        "id": "REQ-004",
        "type": "requirement",
        "label": "Durable portable memory",
        "sub": "REQ-004",
        "refId": "REQ-004"
      },
      {
        "id": "WO-101",
        "type": "workorder",
        "label": "Distill real sessions into c",
        "sub": "done",
        "refId": "WO-101"
      },
      {
        "id": "WO-102",
        "type": "workorder",
        "label": "Route findings into versione",
        "sub": "done",
        "refId": "WO-102"
      },
      {
        "id": "WO-103",
        "type": "workorder",
        "label": "A/B measure token savings",
        "sub": "in_progress",
        "refId": "WO-103"
      },
      {
        "id": "WO-104",
        "type": "workorder",
        "label": "Persist briefings to Backboa",
        "sub": "done",
        "refId": "WO-104"
      },
      {
        "id": "agent/factory-implementer",
        "type": "agent",
        "label": "Factory Implementer",
        "sub": "v2.0.0",
        "refId": "agent/factory-implementer"
      },
      {
        "id": "agent/quality-reviewer",
        "type": "agent",
        "label": "Quality Reviewer",
        "sub": "v1.2.0",
        "refId": "agent/quality-reviewer"
      },
      {
        "id": "skill/creative-franchise-expansion",
        "type": "skill",
        "label": "Creative Franchise Expansion",
        "sub": "v1.0.0",
        "refId": "skill/creative-franchise-expansion"
      },
      {
        "id": "skill/automation-maintenance",
        "type": "skill",
        "label": "Automation Maintenance",
        "sub": "v1.0.0",
        "refId": "skill/automation-maintenance"
      },
      {
        "id": "skill/api-rate-limiting",
        "type": "skill",
        "label": "API Rate Limiting",
        "sub": "v1.0.0",
        "refId": "skill/api-rate-limiting"
      },
      {
        "id": "skill/angular-upgrade",
        "type": "skill",
        "label": "Angular Upgrade",
        "sub": "v1.0.0",
        "refId": "skill/angular-upgrade"
      },
      {
        "id": "skill/command-verification",
        "type": "skill",
        "label": "Command Verification",
        "sub": "v2.0.0",
        "refId": "skill/command-verification"
      },
      {
        "id": "skill/api-security",
        "type": "skill",
        "label": "API Security",
        "sub": "v1.0.0",
        "refId": "skill/api-security"
      },
      {
        "id": "skill/memory-management",
        "type": "skill",
        "label": "Memory Management",
        "sub": "v1.0.0",
        "refId": "skill/memory-management"
      },
      {
        "id": "CAP-R001",
        "type": "capsule",
        "label": "When expanding a creative ",
        "sub": "transfer 40",
        "refId": "CAP-R001"
      },
      {
        "id": "CAP-R002",
        "type": "capsule",
        "label": "Automated hooks can become",
        "sub": "transfer 29",
        "refId": "CAP-R002"
      },
      {
        "id": "CAP-R003",
        "type": "capsule",
        "label": "When integrating third-par",
        "sub": "transfer 37",
        "refId": "CAP-R003"
      },
      {
        "id": "CAP-R004",
        "type": "capsule",
        "label": "When upgrading Angular ver",
        "sub": "transfer 57",
        "refId": "CAP-R004"
      },
      {
        "id": "CAP-R005",
        "type": "capsule",
        "label": "When working with local co",
        "sub": "transfer 55",
        "refId": "CAP-R005"
      },
      {
        "id": "CAP-R006",
        "type": "capsule",
        "label": "Always ensure valid authen",
        "sub": "transfer 54",
        "refId": "CAP-R006"
      },
      {
        "id": "CAP-R007",
        "type": "capsule",
        "label": "When working with local co",
        "sub": "transfer 47",
        "refId": "CAP-R007"
      },
      {
        "id": "CAP-R008",
        "type": "capsule",
        "label": "When dealing with resource",
        "sub": "transfer 50",
        "refId": "CAP-R008"
      },
      {
        "id": "claude-opus-4-8",
        "type": "model",
        "label": "claude-opus-4-8",
        "sub": "session backend",
        "refId": "claude-opus-4-8"
      },
      {
        "id": "ollama-local",
        "type": "model",
        "label": "qwen2.5-coder:14b",
        "sub": "local distiller",
        "refId": "ollama-local"
      },
      {
        "id": "backboard-memory",
        "type": "mcp",
        "label": "Backboard MCP",
        "sub": "connected",
        "refId": "backboard-memory"
      },
      {
        "id": "mem/backboard",
        "type": "memory",
        "label": "Backboard",
        "sub": "Memory Pro hub",
        "refId": "mem/backboard"
      }
    ],
    "links": [
      {
        "source": "WO-101",
        "target": "REQ-001",
        "kind": "implements"
      },
      {
        "source": "WO-102",
        "target": "REQ-002",
        "kind": "implements"
      },
      {
        "source": "WO-103",
        "target": "REQ-003",
        "kind": "implements"
      },
      {
        "source": "WO-104",
        "target": "REQ-004",
        "kind": "implements"
      },
      {
        "source": "agent/factory-implementer",
        "target": "WO-101",
        "kind": "executes"
      },
      {
        "source": "agent/factory-implementer",
        "target": "WO-102",
        "kind": "executes"
      },
      {
        "source": "agent/factory-implementer",
        "target": "skill/creative-franchise-expansion",
        "kind": "uses"
      },
      {
        "source": "agent/factory-implementer",
        "target": "skill/automation-maintenance",
        "kind": "uses"
      },
      {
        "source": "agent/factory-implementer",
        "target": "skill/api-rate-limiting",
        "kind": "uses"
      },
      {
        "source": "agent/factory-implementer",
        "target": "skill/angular-upgrade",
        "kind": "uses"
      },
      {
        "source": "agent/quality-reviewer",
        "target": "WO-103",
        "kind": "executes"
      },
      {
        "source": "agent/quality-reviewer",
        "target": "skill/command-verification",
        "kind": "uses"
      },
      {
        "source": "agent/quality-reviewer",
        "target": "skill/api-security",
        "kind": "uses"
      },
      {
        "source": "agent/quality-reviewer",
        "target": "skill/memory-management",
        "kind": "uses"
      },
      {
        "source": "CAP-R001",
        "target": "skill/creative-franchise-expansion",
        "kind": "produces"
      },
      {
        "source": "CAP-R001",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R001",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R002",
        "target": "skill/automation-maintenance",
        "kind": "produces"
      },
      {
        "source": "CAP-R002",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R002",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R003",
        "target": "skill/api-rate-limiting",
        "kind": "produces"
      },
      {
        "source": "CAP-R003",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R003",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R004",
        "target": "skill/angular-upgrade",
        "kind": "produces"
      },
      {
        "source": "CAP-R004",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R004",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R005",
        "target": "skill/command-verification",
        "kind": "produces"
      },
      {
        "source": "CAP-R005",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R005",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R006",
        "target": "skill/api-security",
        "kind": "produces"
      },
      {
        "source": "CAP-R006",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R006",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R007",
        "target": "skill/command-verification",
        "kind": "produces"
      },
      {
        "source": "CAP-R007",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R007",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "CAP-R008",
        "target": "skill/memory-management",
        "kind": "produces"
      },
      {
        "source": "CAP-R008",
        "target": "claude-opus-4-8",
        "kind": "derives"
      },
      {
        "source": "CAP-R008",
        "target": "mem/backboard",
        "kind": "stores"
      },
      {
        "source": "claude-opus-4-8",
        "target": "mem/backboard",
        "kind": "reads"
      },
      {
        "source": "ollama-local",
        "target": "mem/backboard",
        "kind": "reads"
      },
      {
        "source": "backboard-memory",
        "target": "mem/backboard",
        "kind": "stores"
      }
    ]
  },
  "abTrials": [
    {
      "id": "AB-01",
      "task": "Write a short TypeScript function and explain the key correctness consideration for this task: \"Creative Franchise Expansion\" in a Content Engine codebase.",
      "skillId": "skill/creative-franchise-expansion",
      "model": "qwen2.5-coder:14b",
      "mcp": "ollama-local",
      "withCapsule": {
        "tokens": 381,
        "steps": 1,
        "passed": true,
        "transferScore": 40,
        "durationS": 8,
        "outcome": "Applied capsule finding directly (292 output tokens). Measured proxy: real Ollama token counts (prompt_eval+eval) from one generation WITH vs WITHOUT the capsule finding injected; steps = generations, not agent loops."
      },
      "withoutCapsule": {
        "tokens": 453,
        "steps": 1,
        "passed": true,
        "transferScore": 10,
        "durationS": 11,
        "outcome": "Re-derived the approach cold (400 output tokens). Measured proxy: real Ollama token counts (prompt_eval+eval) from one generation WITH vs WITHOUT the capsule finding injected; steps = generations, not agent loops."
      },
      "verdict": "Injecting the capsule finding cut 72 measured tokens (16%) on this task. Measured proxy on the local model."
    },
    {
      "id": "AB-02",
      "task": "Write a short TypeScript function and explain the key correctness consideration for this task: \"Automation Maintenance\" in a Workspace codebase.",
      "skillId": "skill/automation-maintenance",
      "model": "qwen2.5-coder:14b",
      "mcp": "ollama-local",
      "withCapsule": {
        "tokens": 473,
        "steps": 1,
        "passed": true,
        "transferScore": 29,
        "durationS": 11,
        "outcome": "Applied capsule finding directly (383 output tokens). Measured proxy: real Ollama token counts (prompt_eval+eval) from one generation WITH vs WITHOUT the capsule finding injected; steps = generations, not agent loops."
      },
      "withoutCapsule": {
        "tokens": 435,
        "steps": 1,
        "passed": true,
        "transferScore": 0,
        "durationS": 11,
        "outcome": "Re-derived the approach cold (385 output tokens). Measured proxy: real Ollama token counts (prompt_eval+eval) from one generation WITH vs WITHOUT the capsule finding injected; steps = generations, not agent loops."
      },
      "verdict": "No token saving measured on this single-shot task (measured proxy; agent-loop savings not captured here)."
    },
    {
      "id": "AB-03",
      "task": "Write a short TypeScript function and explain the key correctness consideration for this task: \"API Rate Limiting\" in a Workspace codebase.",
      "skillId": "skill/api-rate-limiting",
      "model": "qwen2.5-coder:14b",
      "mcp": "ollama-local",
      "withCapsule": {
        "tokens": 247,
        "steps": 1,
        "passed": true,
        "transferScore": 37,
        "durationS": 5,
        "outcome": "Applied capsule finding directly (162 output tokens). Measured proxy: real Ollama token counts (prompt_eval+eval) from one generation WITH vs WITHOUT the capsule finding injected; steps = generations, not agent loops."
      },
      "withoutCapsule": {
        "tokens": 404,
        "steps": 1,
        "passed": true,
        "transferScore": 7,
        "durationS": 10,
        "outcome": "Re-derived the approach cold (352 output tokens). Measured proxy: real Ollama token counts (prompt_eval+eval) from one generation WITH vs WITHOUT the capsule finding injected; steps = generations, not agent loops."
      },
      "verdict": "Injecting the capsule finding cut 157 measured tokens (39%) on this task. Measured proxy on the local model."
    }
  ],
  "factoryModules": [
    {
      "id": "refinery",
      "name": "Capsule Refinery",
      "label": "Refinery",
      "blurb": "Compresses real Claude Code sessions into reusable capsules via the local model.",
      "status": "active",
      "stat": {
        "primary": 8,
        "primaryLabel": "capsules",
        "secondary": 10,
        "secondaryLabel": "sessions ingested"
      }
    },
    {
      "id": "foundry",
      "name": "Skill Foundry",
      "label": "Foundry",
      "blurb": "Forges and versions enterprise skills from routed capsule findings.",
      "status": "active",
      "stat": {
        "primary": 7,
        "primaryLabel": "skills",
        "secondary": 8,
        "secondaryLabel": "versions forged"
      }
    },
    {
      "id": "planner",
      "name": "Work Planner",
      "label": "Planner",
      "blurb": "Decomposes intent into agent-ready work orders.",
      "status": "healthy",
      "stat": {
        "primary": 4,
        "primaryLabel": "requirements",
        "secondary": 4,
        "secondaryLabel": "work orders"
      }
    },
    {
      "id": "assembler",
      "name": "Agent Assembler",
      "label": "Assembler",
      "blurb": "Wires versioned skills into the agents that execute work orders.",
      "status": "active",
      "stat": {
        "primary": 2,
        "primaryLabel": "agents",
        "secondary": 7,
        "secondaryLabel": "skills wired"
      }
    },
    {
      "id": "tests",
      "name": "A/B Harness",
      "label": "Tests",
      "blurb": "Measures token savings WITH vs WITHOUT the capsule on the local model.",
      "status": "healthy",
      "stat": {
        "primary": 43032,
        "primaryLabel": "tokens saved",
        "secondary": 63,
        "secondaryLabel": "% adoption"
      }
    },
    {
      "id": "validator",
      "name": "Validator",
      "label": "Validator",
      "blurb": "Scores handoff transfer across six cognitive dimensions.",
      "status": "active",
      "stat": {
        "primary": 46,
        "primaryLabel": "avg transfer",
        "secondary": 3,
        "secondaryLabel": "MCPs wired"
      }
    }
  ]
};

// REAL/COMPUTED dashboard metrics (#6) — derived from `base` every load.
export const data: Dataset = { ...base, metrics: computeMetrics(base) };
